import React from 'react';
import{ SkillSection,
        SkillContainer,
        SkillsRow,
        Column1,
        Column2,
        Box,
        Title,
        Subtitle,
        SkillsGroup,
        Check,
        SkillName,
        SkillLevel,
        SkillData,
        Skill} from './SkillsElements';


function Skills() {
    return (
        <SkillSection id="skills">
            <Title>Habilidades</Title>
            <SkillContainer>
                <SkillsRow>
                    <Column1>
                        <Subtitle>
                            Frontend
                        </Subtitle>
                        <Box>
                            <SkillsGroup>
                                <SkillData>
                                    <Check/>
                                    <Skill>
                                        <SkillName>Html</SkillName>
                                        <SkillLevel>Intermediate</SkillLevel>
                                    </Skill>
                                </SkillData>
                                <SkillData>
                                    <Check/>
                                    <Skill>
                                        <SkillName>CSS</SkillName>
                                        <SkillLevel>Intermediate</SkillLevel>
                                    </Skill>
                                </SkillData>
                                <SkillData>
                                    <Check/>
                                    <Skill>
                                        <SkillName>Javascript</SkillName>
                                        <SkillLevel>Intermediate</SkillLevel>
                                    </Skill>
                                </SkillData>
                                <SkillData>
                                    <Check/>
                                    <Skill>
                                        <SkillName>React</SkillName>
                                        <SkillLevel>Intermediate</SkillLevel>
                                    </Skill>
                                </SkillData>
                            </SkillsGroup>
                            <SkillsGroup>
                                <SkillData>
                                    <Check/>
                                    <Skill>
                                        <SkillName>Less</SkillName>
                                        <SkillLevel>Basic</SkillLevel>
                                    </Skill>
                                </SkillData>
                                <SkillData>
                                    <Check/>
                                    <Skill>
                                        <SkillName>Git</SkillName>
                                        <SkillLevel>Intermediate</SkillLevel>
                                    </Skill>
                                </SkillData>
                                <SkillData>
                                    <Check/>
                                    <Skill>
                                        <SkillName>Python</SkillName>
                                        <SkillLevel>Intermediate</SkillLevel>
                                    </Skill>
                                </SkillData>
                                <SkillData>
                                    <Check/>
                                    <Skill>
                                        <SkillName>Java</SkillName>
                                        <SkillLevel>Basic</SkillLevel>
                                    </Skill>
                                </SkillData>
                            </SkillsGroup>
                        </Box>
                    </Column1>
                    <Column2>
                        <Subtitle>
                        Backend
                        </Subtitle>
                        <Box>
                            <SkillsGroup>
                                <SkillData>
                                    <Check/>
                                    <Skill>
                                        <SkillName>MySQL</SkillName>
                                        <SkillLevel>Basic</SkillLevel>
                                    </Skill>
                                </SkillData>
                                <SkillData>
                                    <Check/>
                                    <Skill>
                                        <SkillName>NodeJS</SkillName>
                                        <SkillLevel>Basic</SkillLevel>
                                    </Skill>
                                </SkillData>
                            </SkillsGroup>
                            <SkillsGroup>
                                <SkillData>
                                    <Check/>
                                    <Skill>
                                        <SkillName>Firebase</SkillName>
                                        <SkillLevel>Basic</SkillLevel>
                                    </Skill>
                                </SkillData>
                            </SkillsGroup>
                        </Box>
                    </Column2>
                </SkillsRow>
            </SkillContainer>
        </SkillSection>
    );
}

export default Skills;
